# Generated by Django 3.2.8 on 2021-10-24 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artists', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MovieListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=50)),
                ('artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieApp.artistsmodel')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieApp.genremodel')),
            ],
        ),
    ]
