# Generated by Django 3.2.8 on 2021-12-27 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_alter_movielistmodel_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielistmodel',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genreby', to='MovieApp.genremodel'),
        ),
    ]
