# Generated by Django 3.2.8 on 2021-12-27 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0003_alter_movielistmodel_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielistmodel',
            name='artists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistsby', to='MovieApp.artistsmodel'),
        ),
    ]
